name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean previous builds
        run: |
          jupyter-book clean book --all || true

      - name: List book files
        run: |
          ls -R book

      - name: Build Jupyter Book
        run: |
          jupyter-book clean book --all || true
          jupyter-book build book
          ls -R book/_build/html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          ghp-import -n -p -f book/_build/html
